### PR TITLE
GPT-XL

### PR DESCRIPTION
**Pull request by Autobot37**
I ran gpt-xl and cpu is producing 334.309779ms per token.
while cuda is producing layernorm error for some reason.
i am attaching this PR to please look at diff and suggest error fix.

also is there way to make it faster?

CPU: Intel Xeon (2) @ 2.199GHz 
GPU: NVIDIA Tesla T4

### CODE REVIEW

**Comment by Autobot37** [comment]
```
Error in layerNormKernel: invalid configuration argument
embedding_dim: 1600
shared_siz: 1600
Aborted (core dumped)
```

```
Error in gemvSumKernel: invalid configuration argument
Aborted (core dumped)
```

**Comment by Autobot37** [comment]
but if i don't execute these two kernels then
Cuda takes 14.616595ms per token.

**Comment by Autobot37** [comment]
In all Cuda kernels i think threads are being launched for embedding size.
but here this is 1600 which surpasses 1024 limit.

**Comment by a1k0n** [comment]
Ah, yeah, that's right. The CUDA kernels are very simplistic and assume <=1024 channels.

**Pull request closed without merging**
